version: 2

workflows:
  version: 2
  build-app-and-image:
    jobs:
      - gradle-app:
          context:
            - dockerhub
            - sportsdata

jobs:
  gradle-app:
#    docker:
#      - image: cimg/openjdk:17.0.6
    machine: true

    working_directory: ~/sportsdata

    steps:
      - checkout
#      - setup_remote_docker:
#          version: 20.10.18
#          docker_layer_caching: true

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./application/build.gradle" }}-{{ checksum "./library/build.gradle" }}-{{ checksum "./sync/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "./application/build.gradle" }}-{{ checksum "./library/build.gradle" }}-{{ checksum "./sync/build.gradle" }}
      - run: ./docker/setup_app_props.sh
      - run: ./gradlew test
      - run: ./gradlew build
      - run: ./gradlew bootJar
      - run: docker build . -f ./docker/Dockerfile -t stefoosh/sportsdata:latest
#      - run: echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
#      - run: docker image push stefoosh/sportsdata:latest